// <auto-generated />
using System;
using ASP_IW5_2018.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP_IW5_2018.Migrations
{
    [DbContext(typeof(PhotoAlbumDbContext))]
    [Migration("20180829144616_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTaken");

                    b.Property<string>("Format");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoAlbum", b =>
                {
                    b.Property<int>("PhotoId");

                    b.Property<int>("AlbumId");

                    b.HasKey("PhotoId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("PhotoAlbums");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoItem", b =>
                {
                    b.Property<int>("PhotoId");

                    b.Property<int>("ItemId");

                    b.HasKey("PhotoId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PhotoItems");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoPerson", b =>
                {
                    b.Property<int>("PhotoId");

                    b.Property<int>("PersonId");

                    b.HasKey("PhotoId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PhotoPersons");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoResolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Height");

                    b.Property<int>("PhotoId");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("PhotoResolution");
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoAlbum", b =>
                {
                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Album", "Album")
                        .WithMany("PhotoAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Photo", "Photo")
                        .WithMany("PhotoAlbums")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoItem", b =>
                {
                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Item", "Item")
                        .WithMany("PhotoItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Photo", "Photo")
                        .WithMany("PhotoItems")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoPerson", b =>
                {
                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Person", "Person")
                        .WithMany("PhotoPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Photo", "Photo")
                        .WithMany("PhotoPersons")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ASP_IW5_2018.Models.PhotoAlbum.PhotoResolution", b =>
                {
                    b.HasOne("ASP_IW5_2018.Models.PhotoAlbum.Photo", "Photo")
                        .WithOne("Resolution")
                        .HasForeignKey("ASP_IW5_2018.Models.PhotoAlbum.PhotoResolution", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
